[project]
name = "events-collector"
version = "0.1.0"
description = "standalone events collector service"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "fastapi[all]>=0.111.0,<0.112.0",
    "uvicorn>=0.27.0.post1,<0.28.0",
    "pydantic-settings>=2.3.4,<3.0.0",
    "pyjwt[crypto]>=2.8.0,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "shared-lib",
]

[tool.uv.sources]
shared-lib = { workspace = true }
