[project]
name = "ecom"
version = "0.1.0"
description = "root of the workspace"
authors = [{ name = "kirill", email = "Richi.mosberg@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi[all]>=0.111.0,<0.112.0",
    "alembic>=1.13.1,<2.0.0",
    "email-validator>=2.2.0,<3.0.0",
    "uvicorn>=0.27.0.post1,<0.28.0",
    "black>=24.1.1,<25.0.0",
    "asyncpg==0.29.0",
    "pyjwt[crypto]>=2.8.0,<3.0.0",
    "pillow>=10.2.0,<11.0.0",
    "aioredis>=2.0.1,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "anyio>=4.2.0,<5.0.0",
    "pytest>=7.3.2,<8.0.0",
    "psycopg2==2.9.9",
    "trio>=0.24.0,<0.25.0",
    "celery[redis]>=5.4.0,<6.0.0",
    "image>=1.5.33,<2.0.0",
    "aiofiles>=23.2.1,<24.0.0",
    "python-json-logger>=2.0.7,<3.0.0",
    "aiohttp>=3.9.3,<4.0.0",
    "aiobotocore>=2.13.1,<3.0.0",
    "pyarrow>=19.0.1,<20.0.0",
    "pytest-asyncio==0.21.1",
    "sqlalchemy>=2.0.30,<3.0.0",
    "ruff>=0.5.1,<0.6.0",
    "bcrypt>=4.2.0,<5.0.0",
    "pika>=1.3.2,<2.0.0",
    "dateparser>=1.2.0,<2.0.0",
    "yookassa>=3.3.0,<4.0.0",
    "var-dump>=1.2,<2.0",
    "flower>=2.0.1,<3.0.0",
    "loguru>=0.7.3,<0.8.0",
    "aiokafka>=0.12.0",
]

[tool.uv]
package = false

[tool.uv.sources]
auth = { workspace = true }
shared-lib = { workspace = true }

[tool.uv.workspace]
members = [
    "marketplace-backend",
    "marketplace-backend/scripts",
    "auth",
    "recommendations",
    "events_collector",
    "event-saver",
    "shared-lib",
    "training-features-etl",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "isort>=7.0.0,<8.0.0",
    "pylint>=3",
]
