version: '3.9'

services:
  web:
    container_name:
      shop_application

    build: ..

    command: bash -c "uvicorn application.cmd:app --reload --host 0.0.0.0 --port 8000"

    env_file:
      - ../core/config/.env
      - ../auth/.env

    volumes:
      - shared_volume:/project/application/static/images
      - ../application/static/images:/project/application/static/images

    ports:
      - "8000:8000"

    depends_on:
      - db
      - celery

  db:
    container_name:
      postgres_database

    image: postgres:15

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5433
      - POSTGRES_DB=proj_db

    ports:
      - "5432:5432"

  migrator:
    build:
       context: ..

    deploy:
       restart_policy:
         condition: on-failure
         max_attempts: 7

    command: bash -c "alembic revision --autogenerate && alembic upgrade head"

    depends_on:
       - db


  redis:
   container_name:
     redis_container

   image: redis:7

   ports:
     - "6379:6379"

  celery:
   container_name:
     celery_container

   build:
    context:
      ..

   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379

   volumes:
     - shared_volume:/project/application/static/images

   depends_on:
     - redis

   command: bash -c "celery -A infrastructure.celery.app:celery worker --loglevel=INFO"


volumes:
  shared_volume:
