version: '3.9'

services:
  web:
    container_name:
      shop_application

    build: ..

    command: bash -c "uvicorn application.cmd:app --reload --host 0.0.0.0 --port 8000"

    environment:
      - MODE=TEST
      - LOG_LEVEL=INFO

      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SERVER=db
      - DB_PORT=5432
      - DB_NAME=proj_db

      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_SERVER=db
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=proj_db_test

      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=richi.mosberg@gmail.com
      - SMTP_PASS=wigfzahnhuzdfwge

      - REDIS_HOST=redis
      - REDIS_PORT=6379

    volumes:
      - shared_volume:/project/application/static/images
      - ../application/static/images:/project/application/static/images

    ports:
      - "8000:8000"

    depends_on:
      - db
      - celery

  db:
    container_name:
      postgres_database

    image: postgres:15

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=proj_db

    ports:
      - "5432:5432"

  migrator:
   build:
     context: ..

   deploy:
     restart_policy:
       condition: on-failure
       max_attempts: 7

   command: bash -c "alembic revision --autogenerate && alembic upgrade head"

   depends_on:
     - db


  redis:
   container_name:
     redis_container

   image: redis:7

   ports:
     - "6379:6379"

  celery:
   container_name:
     celery_container

   build:
     context: ..

   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379

   volumes:
     - shared_volume:/project/application/static/images

   depends_on:
     - redis

   command: bash -c "celery -A application.tasks.celery_init:celery worker --loglevel=INFO"


volumes:
  shared_volume:
