"""first migration

Revision ID: d071dcebfd5c
Revises:
Create Date: 2026-02-21 21:55:15.309452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d071dcebfd5c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        schema="public",
    )
    op.create_table(
        "books",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("isbn", sa.String(), nullable=False),
        sa.Column("rating", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year_of_publication", sa.BIGINT(), nullable=False),
        sa.Column("publisher", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column(
            "price_per_unit", sa.DECIMAL(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "discount",
            sa.DECIMAL(precision=2, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "price_with_discount",
            sa.DECIMAL(),
            sa.Computed(
                "price_per_unit - (price_per_unit * discount*0.01)",
            ),
            nullable=False,
        ),
        sa.Column(
            "number_in_stock", sa.BIGINT(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "number_in_stock >= 0",
            name=op.f("ck_books_ck_books_number_in_stock_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
        sa.UniqueConstraint("isbn", name=op.f("uq_books_isbn")),
        schema="public",
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name="uq_categories_name"),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
        schema="public",
    )
    op.create_table(
        "payment_details",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("payment_provider", sa.String(), nullable=True),
        sa.Column("amount", sa.Double(), server_default="0.0", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_details")),
        schema="public",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role_name", sa.String(), server_default="user", nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="public",
    )
    op.create_table(
        "book_author_assoc",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["public.authors.id"],
            name=op.f("fk_book_author_assoc_author_id_authors"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["public.books.id"],
            name=op.f("fk_book_author_assoc_book_id_books"),
        ),
        sa.PrimaryKeyConstraint(
            "book_id", "author_id", name=op.f("pk_book_author_assoc")
        ),
        schema="public",
    )
    op.create_table(
        "book_category_assoc",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["public.books.id"],
            name=op.f("fk_book_category_assoc_book_id_books"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["public.categories.id"],
            name=op.f("fk_book_category_assoc_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint(
            "book_id", "category_id", name=op.f("pk_book_category_assoc")
        ),
        schema="public",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("order_status", sa.String(), server_default="pending", nullable=True),
        sa.Column("order_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_sum", sa.Double(), nullable=False),
        sa.Column("payment_id", sa.BIGINT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["public.payment_details.id"],
            name=op.f("fk_orders_payment_id_payment_details"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
            name=op.f("fk_orders_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        schema="public",
    )
    op.create_table(
        "publishers",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["public.books.id"],
            name=op.f("fk_publishers_book_id_books"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publishers")),
        schema="public",
    )
    op.create_table(
        "shopping_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("total", sa.Numeric(), server_default="0", nullable=False),
        sa.Column("expiration_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
            name=op.f("fk_shopping_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_sessions")),
        sa.UniqueConstraint("user_id", name=op.f("uq_shopping_sessions_user_id")),
        schema="public",
    )
    op.create_index(
        "ix_shopping_sessions",
        "shopping_sessions",
        ["expiration_time"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "book_order_assoc",
        sa.Column("order_id", sa.BIGINT(), nullable=False),
        sa.Column("book_id", sa.BIGINT(), nullable=False),
        sa.Column("count_ordered", sa.BIGINT(), server_default="1", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["public.books.id"],
            name=op.f("fk_book_order_assoc_book_id_books"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["public.orders.id"],
            name=op.f("fk_book_order_assoc_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("order_id", "book_id", name="pk_book_order_assoc"),
        sa.UniqueConstraint(
            "order_id", "book_id", name="uq_book_order_assoc_order_id_book_id"
        ),
        schema="public",
    )
    op.create_table(
        "cart_items",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.BIGINT(), nullable=False),
        sa.Column("quantity", sa.BIGINT(), server_default="1", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["public.books.id"],
            name=op.f("fk_cart_items_book_id_books"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["public.shopping_sessions.id"],
            name=op.f("fk_cart_items_session_id_shopping_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "book_id", name="pk_cart_items"),
        sa.UniqueConstraint(
            "session_id", "book_id", name="uq_cart_items_session_id_book_id"
        ),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_items", schema="public")
    op.drop_table("book_order_assoc", schema="public")
    op.drop_index(
        "ix_shopping_sessions", table_name="shopping_sessions", schema="public"
    )
    op.drop_table("shopping_sessions", schema="public")
    op.drop_table("publishers", schema="public")
    op.drop_table("orders", schema="public")
    op.drop_table("book_category_assoc", schema="public")
    op.drop_table("book_author_assoc", schema="public")
    op.drop_table("users", schema="public")
    op.drop_table("payment_details", schema="public")
    op.drop_table("categories", schema="public")
    op.drop_table("books", schema="public")
    op.drop_table("authors", schema="public")
    # ### end Alembic commands ###
