FROM python:3.12-slim

WORKDIR /project/event-saver

COPY event-saver/pyproject.toml event-saver/README.md ./
COPY event-saver/event_saver ./event_saver

RUN pip install --no-cache-dir .

CMD ["python", "-m", "event_saver.main"]
