FROM quay.io/minio/minio:latest

ENV MINIO_ROOT_USER=minioadmin \
    MINIO_ROOT_PASSWORD=minioadmin

EXPOSE 9000 9001

VOLUME ["/data"]

CMD ["server", "/data", "--console-address", ":9001"]

docker build -t local-minio .
docker run -d --name minio \
  -p 9000:9000 -p 9001:9001 \
  -v ~/minio-data/events:/data \
  local-minio