FROM node:22-alpine

WORKDIR /app/marketplace-frontend

COPY marketplace-frontend/package*.json ./
RUN npm ci

COPY marketplace-frontend ./

RUN npm run build

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
